import IAuthData from "../services/Auth/interfaces/IAuthData";
import IAuctionResult from "../services/CarOnSaleClient/interfaces/IAuctionResult";
/**
 * This file exposes necessary methods to return test data for testing
 * NOTE: Kept actual response with limit 1 as test data, ideally we should use a dummy data
 */
export function getTestAuthData(): IAuthData {
    return {
        token: "testToken",
        authenticated: true,
        userId: "testUser",
        internalUserId: 1,
        internalUserUUID: "testUUID",
        type: 1,
        privileges: "testPrevilge"

    }
}

export function getTestAuctionResult(): IAuctionResult {
    return {
        "items": [
            {
                "id": 6720,
                "label": "Toyota HI-ACE Kasten TD lang (12/2018)",
                "endingTime": "2020-03-18T10:30:00.425Z",
                "state": 2,
                "minimumRequiredAsk": 1000,
                "currentHighestBidValue": 100,
                "numBids": 10,
                "isRatedByDealership": false,
                "isPaidByBuyer": false,
                "locationAddress": null,
                "locationCity": "",
                "locationZip": "90xxx",
                "startedAt": "2020-03-11T12:34:35.380Z",
                "paymentDueDate": null,
                "pickupDueDate": null,
                "_fk_associatedDealershipUser": 1,
                "_fk_associatedVehicle": 6535,
                "_fk_highestBiddingSalesmanUser": null,
                "createdAt": "2019-12-17T16:49:49.868Z",
                "updatedAt": "2020-03-11T12:34:49.034Z",
                "hotBid": true,
                "auctioningIterations": 0,
                "originalMinimumRequiredAsk": null,
                "incomingPaymentConfirmedAt": null,
                "outgoingPaymentConfirmedAt": null,
                "purchaseConfirmedAt": null,
                "pickupConfirmedAt": null,
                "isRatedByBuyer": false,
                "allowInstantPurchase": true,
                "didEndWithInstantPurchase": false,
                "instantPurchasePossibleUntil": "2020-03-11T13:34:35.380Z",
                "priority": null,
                "advertisementHtmlContent": null,
                "instantPurchasePrice": 12333,
                "urlToPickUpAuthorizationDocument": null,
                "urlToInvoice": null,
                "buyerComplaint": 0,
                "locationCountryCode": "DE",
                "purchaseRejectedAt": null,
                "_fk_involvedInternalUser": null,
                "involvedInternalUserRole": null,
                "internalUserCommission": null,
                "_fk_involvedInternalResolverUser": null,
                "internalResolverUserCommission": null,
                "involvedInternalResolverUserRole": null,
                "urlToSignedPickUpAuthorizationDocument": null,
                "internalReferenceText": null,
                "signedPickUpAuthDocumentUploadedAt": null,
                "rejectionReason": null,
                "sellerIban": null,
                "startingBidValue": 0,
                "startingPrice": 0,
                "invoiceReference": null,
                "uuid": "f3bd4c15-bd6a-481d-b916-2f4930f0f2fa",
                "_fk_uuid_vehicle": "82854a95-42f4-4a66-8fa8-891bd3cffd97",
                "_fk_uuid_sellerUser": "4658acde-f4c2-47b9-ba1d-4f024087611e",
                "_fk_uuid_highestBiddingBuyerUser": null,
                "_fk_uuid_involvedInternalUser": null,
                "_fk_uuid_involvedInternalResolverUser": null,
                "needsReview": false,
                "reviewComment": null,
                "pickupPinCode": null,
                "reviewReason": null,
                "urlToPickupBuyerDocument": null,
                "urlToPickupSellerDocument": null,
                "thirdPartyInvoiceReference": null,
                "urlToPaymentSite": null,
                "thirdPartyTransferReference": null,
                "thirdPartyPayoutReference": null,
                "paymentProcess": 0,
                "_fk_uuid_associatedBankAccount": null,
                "draftReviewIterations": null,
                "amIInvolved": false,
                "biddingAgentValue": 0,
                "remainingTimeInSeconds": 500012,
                "remainingTimeForInstantPurchaseInSeconds": null,
                "associatedVehicle": {
                    "id": 6535,
                    "ez": "12/2018",
                    "make": "Toyota",
                    "mileageInKm": 123333,
                    "model": "HI-ACE Kasten TD lang",
                    "vin": "JT1DEXTESTSTUB001",
                    "hadAccident": true,
                    "accidentDescription": "asdfasdfasdf",
                    "category": 6,
                    "color": "Weiß",
                    "doors": 1,
                    "enginePowerInHp": 117,
                    "engineSizeInCcm": 2494,
                    "fuelType": 1,
                    "transmission": 0,
                    "upholstery": 0,
                    "additional": "3. Bremsleuchte - Airbag Fahrer-/Beifahrerseite - Antenne - Anti-Blockier-System (ABS) - Antriebsart: Heckantrieb - Drehzahlmesser - Facelift ab 08 / 2006 - Frontscheibe Verbundglas - Getriebe 5-Gang - Heckscheibe heizbar - Heckscheibenwischer - Karosserie/Aufbau: Kasten - Kopfstützen vorn - Lenksäule (Lenkrad) höhenverstellbar - Leuchtweitenregelung - Motor 2,5 Ltr. - 86 kW Turbodiesel - Nebelschlussleuchte - Radiovorbereitung, 2 Lautsprecher - Radstand 3430 mm - Scheinwerfer H4 - Seitenaufprallschutz - Servolenkung - Wegfahrsperre - Flügeltür am Heck - Klimaanlage - Komfort-Paket",
                    "ac": 1,
                    "coupling": 0,
                    "headlights": 0,
                    "navigation": 0,
                    "parkingAssistance": 0,
                    "sportPackage": 0,
                    "sunRoof": 0,
                    "vehicleHeater": 0,
                    "fullServiceHistory": false,
                    "huReportExists": false,
                    "lastCheckAtMileage": null,
                    "lastHu": null,
                    "numKeys": 1,
                    "numPreOwners": 1,
                    "vatIdReportable": false,
                    "urlToAttachment1": null,
                    "urlToAttachment2": null,
                    "urlToAttachment3": null,
                    "additionalDamages": "asdfasdf",
                    "estimatedValue": 13863,
                    "urlToVehicleSummarySheet": "https://res.cloudinary.com/castle-tech-gmbh/image/upload/v1583930088/k9jzcd0exczdnmk85ems.pdf",
                    "isReadyToDrive": true,
                    "euroNorm": "E4",
                    "dimensionWidthInCm": 1800,
                    "dimensionHeightInCm": 1980,
                    "dimensionLengthInCm": 5240,
                    "unloadedWeightInKg": 1810,
                    "vehicleCondition": null,
                    "numSeats": 3,
                    "isReimportedVehicle": true,
                    "datBaseModelRaw": "HI-ACE (1996->)",
                    "basedOnInternalVehicleExpertReport": false,
                    "isCreatedFromVehicleReport": null,
                    "seriesEquipments": [
                        "3. Bremsleuchte",
                        "Airbag Fahrer-/Beifahrerseite",
                        "Antenne",
                        "Anti-Blockier-System (ABS)",
                        "Antriebsart: Heckantrieb",
                        "Drehzahlmesser",
                        "Facelift ab 08 / 2006",
                        "Frontscheibe Verbundglas",
                        "Getriebe 5-Gang",
                        "Heckscheibe heizbar",
                        "Heckscheibenwischer",
                        "Karosserie/Aufbau: Kasten",
                        "Kopfstützen vorn",
                        "Lenksäule (Lenkrad) höhenverstellbar",
                        "Leuchtweitenregelung",
                        "Motor 2,5 Ltr. - 86 kW Turbodiesel",
                        "Nebelschlussleuchte",
                        "Radiovorbereitung, 2 Lautsprecher",
                        "Radstand 3430 mm",
                        "Scheinwerfer H4",
                        "Seitenaufprallschutz",
                        "Servolenkung",
                        "Wegfahrsperre"
                    ],
                    "specialEquipments": [
                        "Flügeltür am Heck",
                        "Klimaanlage",
                        "Komfort-Paket"
                    ],
                    "isServiceHistoryAvailable": null,
                    "uuid": "82854a95-42f4-4a66-8fa8-891bd3cffd97",
                    "attachments": [
                        {
                            "url": null,
                            "rawData": null,
                            "mimeType": null,
                            "encoding": null
                        },
                        {
                            "url": null,
                            "rawData": null,
                            "mimeType": null,
                            "encoding": null
                        },
                        {
                            "url": null,
                            "rawData": null,
                            "mimeType": null,
                            "encoding": null
                        }
                    ],
                    "damages": [
                        {
                            "id": 4264,
                            "location": 4,
                            "type": 1,
                            "description": "asdfasdf",
                            "_fk_associatedVehicle": 6535,
                            "urlToImage": null,
                            "uuid": "115bd028-9bbb-4d89-b367-171c189d8022",
                            "_fk_uuid_vehicle": "82854a95-42f4-4a66-8fa8-891bd3cffd97"
                        }
                    ],
                    "vehicleImages": [
                        {
                            "rawData": null,
                            "url": "https://res.cloudinary.com/castle-tech-gmbh/image/upload/v1579170287/lokpwdfiwcjiomoey6em.jpg",
                            "_fk_associatedVehicle": 6535,
                            "_fk_uuid_vehicle": "82854a95-42f4-4a66-8fa8-891bd3cffd97",
                            "perspective": 0,
                            "encoding": null,
                            "mimeType": null
                        },
                        {
                            "rawData": null,
                            "url": "https://res.cloudinary.com/castle-tech-gmbh/image/upload/v1579170287/rjeygeke1rfhczbgf9qv.jpg",
                            "_fk_associatedVehicle": 6535,
                            "_fk_uuid_vehicle": "82854a95-42f4-4a66-8fa8-891bd3cffd97",
                            "perspective": 1,
                            "encoding": null,
                            "mimeType": null
                        },
                        {
                            "rawData": null,
                            "url": "https://res.cloudinary.com/castle-tech-gmbh/image/upload/v1579170287/pl0hlqo8sc7uyrr9p4id.jpg",
                            "_fk_associatedVehicle": 6535,
                            "_fk_uuid_vehicle": "82854a95-42f4-4a66-8fa8-891bd3cffd97",
                            "perspective": 2,
                            "encoding": null,
                            "mimeType": null
                        },
                        {
                            "rawData": null,
                            "url": "https://res.cloudinary.com/castle-tech-gmbh/image/upload/v1579170287/czxpx7bppollgfbtgqqd.jpg",
                            "_fk_associatedVehicle": 6535,
                            "_fk_uuid_vehicle": "82854a95-42f4-4a66-8fa8-891bd3cffd97",
                            "perspective": 3,
                            "encoding": null,
                            "mimeType": null
                        }
                    ],
                    "imageUrls": {
                        "leftSide": {
                            "rawData": null,
                            "url": "https://res.cloudinary.com/castle-tech-gmbh/image/upload/v1579170287/lokpwdfiwcjiomoey6em.jpg",
                            "_fk_associatedVehicle": 6535,
                            "_fk_uuid_vehicle": "82854a95-42f4-4a66-8fa8-891bd3cffd97",
                            "perspective": 0,
                            "encoding": null,
                            "mimeType": null
                        },
                        "leftSideBack": {
                            "rawData": null,
                            "url": "https://res.cloudinary.com/castle-tech-gmbh/image/upload/v1579170287/rjeygeke1rfhczbgf9qv.jpg",
                            "_fk_associatedVehicle": 6535,
                            "_fk_uuid_vehicle": "82854a95-42f4-4a66-8fa8-891bd3cffd97",
                            "perspective": 1,
                            "encoding": null,
                            "mimeType": null
                        },
                        "rightSide": {
                            "rawData": null,
                            "url": "https://res.cloudinary.com/castle-tech-gmbh/image/upload/v1579170287/pl0hlqo8sc7uyrr9p4id.jpg",
                            "_fk_associatedVehicle": 6535,
                            "_fk_uuid_vehicle": "82854a95-42f4-4a66-8fa8-891bd3cffd97",
                            "perspective": 2,
                            "encoding": null,
                            "mimeType": null
                        },
                        "interior": {
                            "rawData": null,
                            "url": "https://res.cloudinary.com/castle-tech-gmbh/image/upload/v1579170287/czxpx7bppollgfbtgqqd.jpg",
                            "_fk_associatedVehicle": 6535,
                            "_fk_uuid_vehicle": "82854a95-42f4-4a66-8fa8-891bd3cffd97",
                            "perspective": 3,
                            "encoding": null,
                            "mimeType": null
                        },
                        "front": null,
                        "rightSideBack": null,
                        "back": null,
                        "trunk": null,
                        "other1": null,
                        "other2": null,
                        "other3": null,
                        "other4": null,
                        "other5": null,
                        "other6": null,
                        "other7": null,
                        "other8": null,
                        "other9": null,
                        "other10": null,
                        "other11": null,
                        "other12": null,
                        "other13": null,
                        "other14": null,
                        "other15": null,
                        "other16": null
                    }
                },
                "amIHighestBidder": false,
                "sellerContact": null,
                "rating": null,
                "transportationTask": {
                    "id": 432,
                    "netPrice": 435,
                    "grossPrice": 517,
                    "state": 1,
                    "_fk_associatedAuction": 6720,
                    "_fk_associatedBuyer": 1,
                    "createdAt": "2020-03-11T17:50:14.978Z",
                    "updatedAt": "2020-03-11T17:50:15.036Z",
                    "distanceInKm": 666,
                    "internalNetPrice": 0,
                    "bookedAt": null,
                    "_fk_transportationProvider": null,
                    "assignedAt": null,
                    "urlToHandoverProtocolDocument": null,
                    "discountedNetPrice": 395,
                    "invoiceReference": null,
                    "_fk_uuid_auction": "f3bd4c15-bd6a-481d-b916-2f4930f0f2fa",
                    "_fk_uuid_buyerUser": "ce5e3d7f-3a3d-4fde-96bc-986d5f483df8",
                    "_fk_uuid_transportationProvider": null,
                    "uuid": "48914cf9-26e9-42d9-8fd6-194138edc442",
                    "earliestPickupDate": null,
                    "note": null,
                    "_fk_associatedSeller": null,
                    "_fk_uuid_sellerUser": null,
                    "_fk_associatedVehicle": null,
                    "_fk_uuid_associatedVehicle": null,
                    "fromLocationAddressLine": "Flachsröststraße 2",
                    "fromLocationCity": "Nürnberg",
                    "fromLocationZipCode": "90475",
                    "fromLocationCountryCode": "DE",
                    "toLocationAddressLine": "Hutbergstrasse 3",
                    "toLocationCity": "Nürnberg",
                    "toLocationZipCode": "90475",
                    "toLocationCountryCode": "DE"
                },
                "isExternalPaymentAllowed": false,
                "remainingDaysUntilReauctioning": null,
                "remainingDaysUntilLatePickup": null,
                "latePickupFee": null,
                "isTransportationBookingPossible": true,
                "isMinAskReached": false,
                "sellerType": 0,
                "enforceTransportation": false
            }
        ],
        "page": 1,
        "total": 1
    };
}